#!/bin/bash
set -e

if [[ $# -lt 2 || -z "$1" ]]; then # $2 may be empty for delete.
  cmd=$(basename $0)
  echo "使用方法： $cmd <正则> <替换值> [<目标目录/文件> ...]"
  echo "$cmd 将文件内的匹配<正则>的所有字符串替换为<替换值>.
  <替换值>中可以使用\1代表正则中的第一个子模式，\1到\9依次类推。
  如果指定了一个或者多个<目标目录/文件>， 操作的文件范围是所有<目标目录>下的所有文件和所有的<目标文件>，
  否则操作的文件范围是当前目录下的所有文件。
  "
  exit
fi

old=$1 new=$2
if [[ $# = 2 ]]; then
  targets='.'
else
  targets=${@:3}
fi

set -x
sed -i -E "s#$old#$new#g" $(grep -E "$old" $targets -Irl)
