#!/bin/bash
set -e

if [[ $# < 2 || -z "$1" || -z "$2" ]]; then
  cmd=$(basename $0)
  echo "使用方法： $cmd <字符串> <新的字符串> [<目标目录/文件> ...]"
  echo "$cmd 将文件内的<字符串>替换为<新的字符串>.
  如果指定了一个或者多个<目标目录/文件>，
  操作的文件范围是所有<目标目录>下的所有文件和所有的<目标文件>，
  否则操作的文件范围是所有<目标目录>下的所有所有文件。
  "
  exit
fi

old=$1 new=$2
if [[ $# = 2 ]]; then
  targets='.'
else
  targets=${@:2:}
fi

set -x

sed -i "s#$old#$new#g" $(fgrep "$old" $targets -rl)
