#!/bin/bash
shopt -s extglob

prefixes="list detail create update delete save type flags validate libs cache"

exists=''
for i in $prefixes; do
  matched=$(echo $i*)
  test "$matched" != "$i*" && {
    if test -z "$exists"; then
      exists="$matched"
    else
      exists="$exists $matched"
    fi
  }
done

if test -n "$exists"; then
  othersPattern="!(${exists// /|})"
  others=$(echo $othersPattern)
  test "$others" = "$othersPattern" && others=''
  ls -dU --color "${@}" $exists $others
else
  ls "${@}"
fi

